FROM python:3.12-slim-bookworm

# Add this line near the top, after FROM
ARG SECRET_KEY_BUILD

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="/usr/local/bin" sh

WORKDIR /app

# Use this SECRET_KEY during the build process
ENV SECRET_KEY=${SECRET_KEY_BUILD}

# Set the python path to include the backend directory

COPY pyproject.toml /app/
RUN /usr/local/bin/uv sync

COPY ./backend /app/backend/

ENV PYTHONPATH="/app/backend"

COPY ./entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

RUN /usr/local/bin/uv run /app/backend/manage.py collectstatic --noinput

EXPOSE 8000

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["/usr/local/bin/uv", "run", "gunicorn", "config.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]