# Defines a shared memory zone named 'one' that is 10MB in size.
# It will store request states based on the client's IP address ($binary_remote_addr).
# The rate is set to 10 requests per second (10r/s).
limit_req_zone $binary_remote_addr zone=one:10m rate=10r/s;

server {
    listen 80;

    location / {
        # Apply the rate limit defined in the 'one' zone.
        # 'burst=20' allows for short spikes, queuing up to 20 requests.
        # 'nodelay' ensures these burst requests are processed immediately.
        limit_req zone=one burst=20 nodelay;

        # Forward requests to the Gunicorn backend service running on port 8000.
        proxy_pass http://backend:8000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # This location must match Django's STATIC_URL setting
    location /static/ {
        # Serve static files directly from the shared volume.
        alias /app/backend/staticfiles/;
    }
}